//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationUsinAngularjsinMVC.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RHNOMEntities : DbContext
    {
        public RHNOMEntities()
            : base("name=RHNOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cat_cargo> tb_cat_cargo { get; set; }
        public virtual DbSet<tb_cat_lugar> tb_cat_lugar { get; set; }
        public virtual DbSet<tb_msc_contrato> tb_msc_contrato { get; set; }
        public virtual DbSet<tb_msc_empleado> tb_msc_empleado { get; set; }
        public virtual DbSet<tb_msc_expediente> tb_msc_expediente { get; set; }
        public virtual DbSet<tb_cat_cargo_nivel> tb_cat_cargo_nivel { get; set; }
    }
}
