//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationUsinAngularjsinMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cat_lugar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cat_lugar()
        {
            this.tb_cat_lugar1 = new HashSet<tb_cat_lugar>();
            this.tb_msc_expediente = new HashSet<tb_msc_expediente>();
        }
    
        public int id_lugar { get; set; }
        public string nom_lugar { get; set; }
        public Nullable<int> id_lugar_sup { get; set; }
        public string tipo_lugar { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cat_lugar> tb_cat_lugar1 { get; set; }
        public virtual tb_cat_lugar tb_cat_lugar2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_msc_expediente> tb_msc_expediente { get; set; }
    }
}
