//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationUsinAngularjsinMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cat_cargo
    {
        public int id_cargo { get; set; }
        public string desc_cargo { get; set; }
        public string tipo_puesto { get; set; }
        public Nullable<int> periodo_prueba { get; set; }
        public Nullable<int> periodo_puesto { get; set; }
        public bool activo { get; set; }
        public Nullable<bool> tipo_operativo { get; set; }
        public Nullable<bool> aut_acciones_p { get; set; }
        public Nullable<bool> comision { get; set; }
        public Nullable<bool> pago_vac_automatica { get; set; }
    }
}
