//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationUsinAngularjsinMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_msc_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_msc_empleado()
        {
            this.tb_msc_contrato = new HashSet<tb_msc_contrato>();
            this.tb_msc_empleado1 = new HashSet<tb_msc_empleado>();
        }
    
        public string id_empleado { get; set; }
        public int id_expediente { get; set; }
        public Nullable<bool> acciones_personal { get; set; }
        public string id_jefe { get; set; }
        public byte[] foto { get; set; }
        public byte[] firma { get; set; }
        public string num_cuenta { get; set; }
        public Nullable<int> id_banco { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_msc_contrato> tb_msc_contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_msc_empleado> tb_msc_empleado1 { get; set; }
        public virtual tb_msc_empleado tb_msc_empleado2 { get; set; }
    }
}
